version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker -providers.file.filename=/etc/traefik/dynamic-config.yml
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443" 
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml 
      - ./dynamic-config.yml:/etc/traefik/dynamic-config.yml  # Configuration dynamique de Traefik
  whoami:
    image: traefik/whoami
    deploy:
      replicas: 3  # Cela démarre trois instances de whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

