version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_passwd:/mosquitto/config/mosquitto_passwd
    networks:
      - mqtt_network

  simulator:
    build: .
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_URL: mqtt://mqtt:1884
      DATA_FREQUENCY: ${DATA_FREQUENCY:-5000}
      SENSOR_COUNT: ${SENSOR_COUNT:-4}
      MQTT_QOS: ${MQTT_QOS:-0}
    env_file:
      - .env
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge
