services:
<<<<<<< HEAD
=======
  # homeassistant:
  #   image: homeassistant/home-assistant:stable
  #   container_name: homeassistant
  #   privileged: true
  #   restart: unless-stopped
  #   volumes:
  #     - ./homeassistant:/config
  #   ports:
  #     - 8123:8123
>>>>>>> origin/dev
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    platform: linux/amd64 
    restart: unless-stopped
    ports:
      - 1884:1884
    volumes:
<<<<<<< HEAD
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    platform: linux/arm/v6
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
  wait-service:
    build: .
    container_name: wait-service
    depends_on:
      homeassistant:
        condition: service_started
      mqtt:
        condition: service_healthy
=======
      - ./data/mosquitto:/mosquitto/data
      - ./log/mosquitto:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto_passwd:/mosquitto/config/mosquitto_passwd
    networks:
      - mqtt_network
  simulator:
    build: .
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_URL: mqtt://mqtt:1884
      DATA_FREQUENCY: ${DATA_FREQUENCY:-5000}
      SENSOR_COUNT: ${SENSOR_COUNT:-4}
      MQTT_QOS: ${MQTT_QOS:-0}
    env_file:
      - ./mosquitto/.env
    networks:
      - mqtt_network
      - app_network
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - 6380:6379     # Port Redis
      - 8001:8001     # Port Redis Insight
    volumes:
      - ./data/redis:/data
      - ./redis/redis-stack.conf:/redis-stack.conf # Optionnel : Fichier de configuration personnalisé
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes  # Activer la persistance des données
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge
  app_network:
    external: true


>>>>>>> origin/dev
