services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    platform: linux/arm/v6
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
  wait-service:
    build: .
    container_name: wait-service
    depends_on:
      homeassistant:
        condition: service_started
      mqtt:
        condition: service_healthy